version: "3.8"

services:
  backend:
    build: ./functions
    ports:
      - "3001:3001"
    env_file:
      - ./functions/.env
    volumes:
      - ./functions:/app  # ✅ Mount entire backend folder to container
      - /app/node_modules  # ✅ Ensure node_modules stays inside container
    depends_on:
      - frontend
    restart: unless-stopped  # ✅ Ensures it restarts on failure
    command: ["npm", "run", "dev"]  # ✅ Use nodemon instead of node

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
