version: "3.8"

services:
  backend:
    build: ./functions
    ports:
      - "3001:3001"
    env_file:
      - ./functions/.env
    volumes:
      - ./functions/firebase-service-account.json:/app/firebase-service-account.json
    depends_on:
      - frontend
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
