version: "3.8"

services:
  backend:
    build: ./functions
    ports:
      - "3001:3001"
    env_file:
      - ./functions/.env
    volumes:
      - ./functions:/app  # ✅ Mount entire backend folder
    depends_on:
      - frontend
    restart: unless-stopped
    command: ["npm", "run", "dev"]

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./frontend:/app  # ✅ Mount frontend but keep container's own node_modules
    restart: unless-stopped
